begin;

create table if not exists public.admins (
    user_id uuid primary key references auth.users (id) on delete cascade,
    role text not null default 'admin',
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.admins
add column if not exists role text not null default 'admin';

alter table public.admins add column if not exists name text default '';
alter table public.admins add column if not exists email text default '';
alter table public.admins add column if not exists status text not null default 'active';

do $$
begin
    alter table public.admins
    add constraint admins_role_check check (role in ('owner', 'admin'));
exception
    when duplicate_object then null;
end $$;

create table if not exists public.apartments (
    id bigint generated by default as identity primary key,
    name text not null,
    location text not null,
    city text,
    neighborhood text,
    price integer not null check (price >= 0),
    bedrooms integer not null check (bedrooms >= 0),
    bathrooms integer not null check (bathrooms >= 0),
    size integer not null check (size >= 0),
    image text not null,
    images text[] not null default '{}',
    description text default '',
    badge text default '',
    type text default 'Apartamento',
    rating numeric(2,1),
    reviews integer,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.apartments add column if not exists status text not null default 'active';
alter table public.apartments add column if not exists featured boolean not null default false;
alter table public.apartments add column if not exists verified boolean not null default true;
alter table public.apartments add column if not exists views integer not null default 0;
alter table public.apartments add column if not exists coordinates jsonb;

create table if not exists public.rental_inquiries (
    id bigint generated by default as identity primary key,
    apartment_id bigint references public.apartments (id) on delete set null,
    apartment_name text not null,
    apartment_area text not null,
    full_name text not null,
    email text not null,
    phone text not null,
    dni text not null,
    birth_date date,
    nationality text not null,
    move_in_date date,
    rental_period text not null,
    occupation text not null,
    workplace text not null,
    monthly_income numeric,
    employment_type text not null,
    num_occupants integer,
    has_pets boolean not null default false,
    pets_details text,
    emergency_contact text not null,
    reference_notes text,
    additional_comments text,
    submitted_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.owner_apartment_requests (
    id bigint generated by default as identity primary key,
    owner_name text not null,
    owner_email text not null,
    owner_phone text not null,
    property_name text not null,
    property_type text not null default 'Apartamento',
    location text not null,
    price integer check (price is null or price >= 0),
    bedrooms integer check (bedrooms is null or bedrooms >= 0),
    bathrooms integer check (bathrooms is null or bathrooms >= 0),
    size integer check (size is null or size >= 0),
    description text default '',
    amenities text default '',
    image_url text default '',
    availability_date date,
    status text not null default 'pendiente' check (status in ('pendiente', 'contactado', 'aprobado', 'rechazado')),
    submitted_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    registered date not null default current_date,
    views integer not null default 0,
    status text not null default 'active' check (status in ('active', 'blocked'))
);

create table if not exists public.owners (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    phone text default '',
    apts integer not null default 0,
    payment text not null default 'pending' check (payment in ('paid', 'pending')),
    since date not null default current_date
);

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    sender_name text not null,
    subject text not null,
    message text default '',
    status text not null default 'unread' check (status in ('unread', 'read')),
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null, -- Opcional
    user_name text not null default 'Usuario',
    apartment_name text not null default 'General',
    rating integer not null default 5 check (rating between 1 and 5),
    comment text default '',
    status text not null default 'published' check (status in ('published', 'pending')),
    user_location text default '',
    avatar_url text default '',
    admin_reply text default '',
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.reviews add column if not exists user_name text not null default 'Usuario';
alter table public.reviews add column if not exists apartment_name text not null default 'General';
alter table public.reviews add column if not exists rating integer not null default 5;
alter table public.reviews add column if not exists comment text default '';
alter table public.reviews add column if not exists status text not null default 'published';
alter table public.reviews add column if not exists user_location text default '';
alter table public.reviews add column if not exists avatar_url text default '';
alter table public.reviews add column if not exists admin_reply text default '';

do $$
begin
    -- Compatibilidad con esquemas anteriores donde cada reseña exigía un listing_id.
    -- Este proyecto también usa reseñas generales ("General"), así que listing_id debe ser opcional.
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'reviews'
          and column_name = 'listing_id'
    ) then
        execute 'alter table public.reviews alter column listing_id drop not null';
    end if;
exception
    when others then null;
end $$;

do $$
begin
    alter table public.reviews
    add constraint reviews_rating_check check (rating between 1 and 5);
exception
    when duplicate_object then null;
end $$;

do $$
begin
    alter table public.reviews
    add constraint reviews_status_check check (status in ('published', 'pending'));
exception
    when duplicate_object then null;
end $$;

create table if not exists public.faqs (
    id bigint generated by default as identity primary key,
    question text not null,
    answer text not null,
    sort_order integer not null default 0,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.todos (
    id bigint generated by default as identity primary key,
    text text not null,
    priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
    done boolean not null default false,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activity_logs (
    id bigint generated by default as identity primary key,
    user_email text not null,
    action text not null,
    severity text not null default 'info' check (severity in ('info', 'success', 'warning', 'danger')),
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    owner_name text not null,
    concept text not null,
    amount numeric not null default 0,
    due_date date,
    status text not null default 'pending' check (status in ('pending', 'paid', 'failed')),
    paid_at date,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.calendar_events (
    id bigint generated by default as identity primary key,
    title text not null,
    event_date date not null,
    status text not null default 'active'
);

create table if not exists public.site_settings (
    key text primary key,
    value jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_admin_role_by_email(admin_email text, admin_role text, admin_name text default null)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    if admin_role not in ('owner', 'admin') then
        raise exception 'Rol invalido: %', admin_role;
    end if;

    insert into public.admins (user_id, email, name, role, status)
    select id, email, coalesce(admin_name, raw_user_meta_data->>'name', email), admin_role, 'active'
    from auth.users
    where lower(email) = lower(admin_email)
    on conflict (user_id) do update set
        email = excluded.email,
        name = excluded.name,
        role = excluded.role,
        status = 'active';

    if not found then
        raise exception 'No existe un usuario Auth con email %', admin_email;
    end if;
end;
$$;

grant execute on function public.set_admin_role_by_email(text, text, text) to authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_apartments_updated_at on public.apartments;
create trigger set_apartments_updated_at
before update on public.apartments
for each row execute function public.set_updated_at();

drop trigger if exists set_owner_apartment_requests_updated_at on public.owner_apartment_requests;
create trigger set_owner_apartment_requests_updated_at
before update on public.owner_apartment_requests
for each row execute function public.set_updated_at();

alter table public.admins enable row level security;
alter table public.apartments enable row level security;
alter table public.rental_inquiries enable row level security;
alter table public.owner_apartment_requests enable row level security;
alter table public.app_users enable row level security;
alter table public.owners enable row level security;
alter table public.messages enable row level security;
alter table public.reviews enable row level security;
alter table public.faqs enable row level security;
alter table public.todos enable row level security;
alter table public.activity_logs enable row level security;
alter table public.payments enable row level security;
alter table public.calendar_events enable row level security;
alter table public.site_settings enable row level security;

-- Eliminar TODAS las políticas antiguas para garantizar que no haya recursión infinita
do $$
declare
    r record;
begin
    for r in (select policyname, tablename from pg_policies where schemaname = 'public' and tablename in ('admins', 'apartments', 'rental_inquiries', 'owner_apartment_requests', 'app_users', 'owners', 'messages', 'reviews', 'faqs', 'todos', 'activity_logs', 'payments', 'calendar_events', 'site_settings')) loop
        execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
    end loop;
end $$;

create policy "Authenticated can read admins"
on public.admins
for select
to authenticated
using (true);

create policy "Authenticated can manage admins"
on public.admins
for all
to authenticated
using (true)
with check (true);

create policy "Public can read apartments"
on public.apartments
for select
to public
using (true);

create policy "Admins can insert apartments"
on public.apartments
for insert
to authenticated
with check (exists (select 1 from public.admins where user_id = auth.uid()));

create policy "Admins can update apartments"
on public.apartments
for update
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()))
with check (exists (select 1 from public.admins where user_id = auth.uid()));

create policy "Admins can delete apartments"
on public.apartments
for delete
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()));

create policy "Public can insert rental inquiries"
on public.rental_inquiries
for insert
to public
with check (true);

create policy "Admins can read rental inquiries"
on public.rental_inquiries
for select
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()));

create policy "Public can insert owner apartment requests"
on public.owner_apartment_requests
for insert
to public
with check (status = 'pendiente');

create policy "Admins can read owner apartment requests"
on public.owner_apartment_requests
for select
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()));

create policy "Admins can update owner apartment requests"
on public.owner_apartment_requests
for update
to authenticated
using (exists (select 1 from public.admins where user_id = auth.uid()))
with check (exists (select 1 from public.admins where user_id = auth.uid()));

do $$
declare
    t text;
begin
    foreach t in array array['app_users','owners','messages','reviews','faqs','todos','activity_logs','payments','calendar_events','site_settings'] loop
        execute format('create policy "Admins can read %1$s" on public.%1$I for select to authenticated using (exists (select 1 from public.admins where user_id = auth.uid()))', t);
        execute format('create policy "Admins can insert %1$s" on public.%1$I for insert to authenticated with check (exists (select 1 from public.admins where user_id = auth.uid()))', t);
        execute format('create policy "Admins can update %1$s" on public.%1$I for update to authenticated using (exists (select 1 from public.admins where user_id = auth.uid())) with check (exists (select 1 from public.admins where user_id = auth.uid()))', t);
        execute format('create policy "Admins can delete %1$s" on public.%1$I for delete to authenticated using (exists (select 1 from public.admins where user_id = auth.uid()))', t);
    end loop;
end $$;

insert into storage.buckets (id, name, public)
values ('apartment-images', 'apartment-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read apartment images" on storage.objects;
create policy "Public can read apartment images"
on storage.objects
for select
to public
using (bucket_id = 'apartment-images');

drop policy if exists "Admins can upload apartment images" on storage.objects;
create policy "Admins can upload apartment images"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
);

drop policy if exists "Admins can update apartment images" on storage.objects;
create policy "Admins can update apartment images"
on storage.objects
for update
to authenticated
using (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
)
with check (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
);

drop policy if exists "Admins can delete apartment images" on storage.objects;
create policy "Admins can delete apartment images"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'apartment-images'
    and exists (select 1 from public.admins where user_id = auth.uid())
);

insert into public.apartments (
    name, location, city, neighborhood, price, bedrooms, bathrooms, size, image, images, description, badge, type, rating, reviews
)
select *
from (
    values
    ('Apartamento Moderno en el Centro', 'Madrid, España', 'Madrid', 'Centro', 1200, 2, 2, 85, 'images/apartment1.jpg', array['images/apartment1.jpg','images/apartment1-1.jpg','images/apartment1-2.jpg']::text[], 'Apartamento moderno y luminoso, ideal para profesionales de la salud.', 'Destacado', 'Apartamento', 5.0, 24),
    ('Apartamento Espacioso con Vista', 'Barcelona, España', 'Barcelona', 'Eixample', 1500, 3, 2, 120, 'images/apartment2.jpg', array['images/apartment2.jpg','images/apartment2-1.jpg','images/apartment2-2.jpg']::text[], 'Espacioso apartamento con excelente ubicación y mucha luz natural.', 'Nuevo', 'Apartamento', 4.5, 18),
    ('Apartamento Céntrico y Acogedor', 'Valencia, España', 'Valencia', 'Ruzafa', 1000, 1, 1, 60, 'images/apartment3.jpg', array['images/apartment3.jpg','images/apartment3-1.jpg','images/apartment3-2.jpg']::text[], 'Perfecto para estancias cómodas con acceso rápido a zonas clave.', '', 'Apartamento', 4.0, 12),
    ('Loft Moderno en Malasaña', 'Madrid, España', 'Madrid', 'Malasaña', 1800, 2, 2, 95, 'images/apartment4.jpg', array['images/apartment4.jpg']::text[], 'Loft moderno con acabados premium y excelente conectividad.', '', 'Loft', 4.8, 32),
    ('Dúplex Acogedor', 'Sevilla, España', 'Sevilla', 'Triana', 900, 2, 1, 75, 'images/apartment5.jpg', array['images/apartment5.jpg']::text[], 'Dúplex funcional y acogedor, ideal para una estancia prolongada.', '', 'Dúplex', 4.3, 15),
    ('Penthouse con Vistas al Mar', 'Barcelona, España', 'Barcelona', 'Barceloneta', 2200, 3, 3, 150, 'images/apartment6.jpg', array['images/apartment6.jpg']::text[], 'Penthouse exclusivo con vistas al mar y grandes espacios.', '', 'Penthouse', 4.9, 45),
    ('Estudio Minimalista', 'Madrid, España', 'Madrid', 'Lavapiés', 750, 1, 1, 45, 'images/apartment7.jpg', array['images/apartment7.jpg']::text[], 'Estudio minimalista y práctico en zona céntrica.', '', 'Estudio', 4.2, 8),
    ('Casa con Jardín', 'Valencia, España', 'Valencia', 'Campanar', 2500, 4, 3, 200, 'images/apartment8.jpg', array['images/apartment8.jpg']::text[], 'Casa amplia con jardín privado y espacios familiares.', '', 'Casa', 4.7, 28),
    ('Apartamento Cerca del Hospital', 'Madrid, España', 'Madrid', 'Chamberí', 1100, 2, 1, 70, 'images/apartment9.jpg', array['images/apartment9.jpg']::text[], 'Ubicación estratégica para profesionales que trabajan en hospitales cercanos.', '', 'Apartamento', 4.6, 21),
    ('Apartamento Luminoso', 'Barcelona, España', 'Barcelona', 'Gràcia', 1350, 2, 1, 75, 'images/apartment10.jpg', array['images/apartment10.jpg']::text[], 'Apartamento luminoso con distribución funcional y ambiente tranquilo.', '', 'Apartamento', 4.4, 19)
) as seed(name, location, city, neighborhood, price, bedrooms, bathrooms, size, image, images, description, badge, type, rating, reviews)
where not exists (select 1 from public.apartments);

insert into public.reviews (user_name, user_location, apartment_name, rating, comment, status, avatar_url, admin_reply)
select * from (
    values 
    ('María García', 'Madrid', 'General', 5, 'Encontré mi apartamento ideal en menos de una semana.', 'published', 'images/avatar1.jpg', '¡Muchas gracias María!'),
    ('Carlos Rodríguez', 'Barcelona', 'General', 5, 'Excelente servicio y apartamentos de calidad.', 'published', 'images/avatar2.jpg', ''),
    ('Ana Martínez', 'Valencia', 'General', 5, 'La mejor experiencia de alquiler que he tenido.', 'published', 'images/avatar3.jpg', ''),
    ('Pedro Sanz', 'Sevilla', 'Apartamento Moderno', 2, 'El proceso fue un poco lento para mi gusto.', 'published', 'images/avatar1.jpg', 'Lamentamos la demora.')
) as seed(user_name, user_location, apartment_name, rating, comment, status, avatar_url, admin_reply)
where not exists (select 1 from public.reviews);

-- IMPORTANTE:
-- Supabase Auth guarda usuarios en auth.users, pero el dashboard solo deja entrar
-- a usuarios que tambien tengan una fila en public.admins.
-- Despues de crear el usuario en Authentication > Users, registra su rol asi:
--
-- insert into public.admins (user_id, role)
-- select id, 'owner'
-- from auth.users
-- where email = 'owner@vitalstays.com'
-- on conflict (user_id) do update set role = excluded.role;
--
-- Para un administrador normal usa role = 'admin'.

commit;
